<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class GameLevelingOrder extends Model
{
    public $fillable = [
        'trade_no',
        'status',
        'platform_id',
        'platform_no',
        'game_id',
        'game_name',
        'amount',
        'security_deposit',
        'efficiency_deposit',
        'poundage',
        'get_amount',
        'user_id',
        'username',
        'parent_user_id',
        'parent_username',
        'take_user_id',
        'take_username',
        'take_parent_user_id',
        'take_parent_username',
        'order_type_id',
        'game_type_id',
        'game_class_id',
        'region_id',
        'region_name',
        'server_id',
        'server_name',
        'game_leveling_type_id',
        'game_leveling_type_name',
        'title',
        'day',
        'hour',
        'game_account',
        'game_password',
        'game_role',
        'user_phone',
        'user_qq',
        'customer_service_name',
        'seller_nick',
        'pre_sale',
        'explain',
        'requirement',
        'take_order_password',
        'player_name',
        'player_phone',
        'player_qq',
        'take_at',
        'price_increase_step',
        'price_ceiling',
        'apply_complete_at',
        'complete_at',
        'source',
        'top',
        'top_at',
        'parent_user_phone',
        'parent_user_qq',
        'take_user_qq',
        'take_user_phone',
        'take_parent_phone',
        'take_parent_qq',
        'created_at',
        'updated_at',
    ];
}
